import json
import os
import sys
from typing import Any

import requests
from supabase import create_client


SUPABASE_URL = os.environ["SUPABASE_URL"]
SUPABASE_KEY = os.environ["SUPABASE_SERVICE_ROLE_KEY"]
OPENAI_API_KEY = os.environ["OPENAI_API_KEY"]
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")


def update_video(supabase, video_id: str, values: dict[str, Any]) -> None:
    response = (
        supabase.table("video_queue")
        .update(values)
        .eq("id", video_id)
        .execute()
    )

    if not response.data:
        raise RuntimeError("Video sətri yenilənmədi.")


def get_pending_video(supabase):
    response = (
        supabase.table("video_queue")
        .select(
            "*,"
            "channel:channels("
            "id,name,language,niche,custom_prompt,"
            "audience_type,long_min_minutes,long_max_minutes,"
            "short_min_seconds,short_max_seconds"
            ")"
        )
        .eq("status", "pending")
        .order("created_at")
        .limit(1)
        .execute()
    )

    if not response.data:
        return None

    return response.data[0]


def build_prompt(video: dict[str, Any]) -> str:
    channel = video["channel"]
    video_type = video["video_type"]

    if video_type == "short":
        duration = (
            f"{channel['short_min_seconds']}–"
            f"{channel['short_max_seconds']} saniyə"
        )
    else:
        duration = (
            f"{channel['long_min_minutes']}–"
            f"{channel['long_max_minutes']} dəqiqə"
        )

    requested_topic = video.get("topic") or "Mövzunu özün seç"

    return f"""
You are creating original YouTube content.

Channel name: {channel['name']}
Language: {channel['language']}
Niche: {channel['niche']}
Audience: {channel['audience_type']}
Video type: {video_type}
Target duration: {duration}
Requested topic: {requested_topic}
Custom channel instruction: {channel.get('custom_prompt') or 'None'}

Create fully original content.

Return:
- a strong topic
- a high-CTR but honest title
- an SEO-friendly description
- YouTube tags
- hashtags without the # character
- thumbnail text, maximum 5 words
- a complete narration script
- visual search keywords for later stock-video search

Do not copy existing videos.
Do not use misleading claims.
Do not mention that the content was generated by AI.
""".strip()


def generate_content(video: dict[str, Any]) -> dict[str, Any]:
    schema = {
        "type": "object",
        "additionalProperties": False,
        "required": [
            "topic",
            "title",
            "description",
            "tags",
            "hashtags",
            "thumbnail_text",
            "script",
            "visual_keywords",
        ],
        "properties": {
            "topic": {
                "type": "string"
            },
            "title": {
                "type": "string"
            },
            "description": {
                "type": "string"
            },
            "tags": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "hashtags": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "thumbnail_text": {
                "type": "string"
            },
            "script": {
                "type": "string"
            },
            "visual_keywords": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
        },
    }

    response = requests.post(
        "https://api.openai.com/v1/responses",
        headers={
            "Authorization": f"Bearer {OPENAI_API_KEY}",
            "Content-Type": "application/json",
        },
        json={
            "model": OPENAI_MODEL,
            "input": build_prompt(video),
            "text": {
                "format": {
                    "type": "json_schema",
                    "name": "youtube_video_content",
                    "strict": True,
                    "schema": schema,
                }
            },
            "max_output_tokens": 12000,
        },
        timeout=180,
    )

    if not response.ok:
        raise RuntimeError(
            f"OpenAI xətası {response.status_code}: "
            f"{response.text[:1000]}"
        )

    payload = response.json()

    output_text = payload.get("output_text")

    if not output_text:
        for output_item in payload.get("output", []):
            for content in output_item.get("content", []):
                if content.get("type") == "output_text":
                    output_text = content.get("text")
                    break

            if output_text:
                break

    if not output_text:
        raise RuntimeError("OpenAI mətn cavabı qaytarmadı.")

    return json.loads(output_text)


def main() -> None:
    supabase = create_client(
        SUPABASE_URL,
        SUPABASE_KEY,
    )

    video = get_pending_video(supabase)

    if not video:
        print("Növbədə pending video yoxdur.")
        return

    video_id = video["id"]

    print("Video tapıldı:", video_id)
    print("Kanal:", video["channel"]["name"])
    print("Mərhələ: Ssenari və metadata hazırlanır.")

    update_video(
        supabase,
        video_id,
        {
            "status": "generating",
            "error_message": None,
        },
    )

    try:
        content = generate_content(video)

        scene_plan = [
            {
                "query": keyword,
                "seconds": 8,
            }
            for keyword in content["visual_keywords"]
        ]

        update_video(
            supabase,
            video_id,
            {
                "topic": content["topic"],
                "title": content["title"][:100],
                "description": content["description"],
                "tags": content["tags"][:30],
                "hashtags": content["hashtags"][:15],
                "thumbnail_text": content["thumbnail_text"][:80],
                "script": content["script"],
                "scene_plan": scene_plan,
                "status": "generating",
            },
        )

        channel = video["channel"]

        supabase.table("events").insert(
            {
                "owner_id": video["owner_id"],
                "video_id": video_id,
                "channel_id": channel["id"],
                "level": "info",
                "type": "content_generated",
                "message": (
                    "Ssenari, başlıq və YouTube metadata-sı "
                    "uğurla hazırlandı."
                ),
                "payload": {
                    "title": content["title"],
                    "topic": content["topic"],
                },
            }
        ).execute()

        print("Ssenari uğurla yaradıldı.")
        print("Başlıq:", content["title"])
        print("Mövzu:", content["topic"])
        print("Növbəti mərhələ: Səs hazırlanması.")

    except Exception as error:
        update_video(
            supabase,
            video_id,
            {
                "status": "failed",
                "error_message": str(error)[:1500],
            },
        )

        raise


if __name__ == "__main__":
    try:
        main()
    except Exception as error:
        print(
            f"CONTENT GENERATION FAILED: {error}",
            file=sys.stderr,
        )
        raise
