import base64
import os
import subprocess
import sys
from pathlib import Path

from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from supabase import create_client


SUPABASE_URL = os.environ["SUPABASE_URL"]
SUPABASE_KEY = os.environ["SUPABASE_SERVICE_ROLE_KEY"]
GOOGLE_CLIENT_ID = os.environ["GOOGLE_CLIENT_ID"]
GOOGLE_CLIENT_SECRET = os.environ["GOOGLE_CLIENT_SECRET"]
TOKEN_ENCRYPTION_KEY = os.environ["TOKEN_ENCRYPTION_KEY"]


def decode_base64url(value: str) -> bytes:
    padding = "=" * ((4 - len(value) % 4) % 4)
    return base64.urlsafe_b64decode(value + padding)


def decrypt_refresh_token(ciphertext: str) -> str:
    parts = ciphertext.split(".")

    if len(parts) != 3 or parts[0] != "v1":
        raise RuntimeError("Refresh token formatı düzgün deyil.")

    key = base64.b64decode(TOKEN_ENCRYPTION_KEY)

    if len(key) != 32:
        raise RuntimeError(
            "TOKEN_ENCRYPTION_KEY Base64-dən açıldıqda 32 byte olmalıdır."
        )

    iv = decode_base64url(parts[1])
    encrypted = decode_base64url(parts[2])

    return AESGCM(key).decrypt(
        iv,
        encrypted,
        None,
    ).decode("utf-8")


def create_test_video(output_path: Path) -> None:
    command = [
        "ffmpeg",
        "-y",
        "-f",
        "lavfi",
        "-i",
        "color=c=0x111827:s=1280x720:d=6",
        "-f",
        "lavfi",
        "-i",
        "sine=frequency=440:duration=6",
        "-vf",
        (
            "drawtext="
            "fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:"
            "text='AutoTube Studio Upload Test':"
            "fontcolor=white:"
            "fontsize=54:"
            "x=(w-text_w)/2:"
            "y=(h-text_h)/2"
        ),
        "-c:v",
        "libx264",
        "-preset",
        "medium",
        "-crf",
        "20",
        "-pix_fmt",
        "yuv420p",
        "-c:a",
        "aac",
        "-b:a",
        "128k",
        "-shortest",
        "-movflags",
        "+faststart",
        str(output_path),
    ]

    subprocess.run(
        command,
        check=True,
    )


def get_connected_channel(supabase):
    response = (
        supabase.table("channels")
        .select(
            "id,name,youtube_channel_id,youtube_handle,"
            "privacy_status,channel_secrets("
            "refresh_token_cipher,scopes)"
        )
        .not_.is_("youtube_channel_id", "null")
        .limit(1)
        .execute()
    )

    if not response.data:
        raise RuntimeError(
            "Supabase-də qoşulmuş YouTube kanalı tapılmadı."
        )

    channel = response.data[0]
    secrets = channel.get("channel_secrets")

    if isinstance(secrets, list):
        secrets = secrets[0] if secrets else None

    if not secrets:
        raise RuntimeError(
            "Qoşulmuş kanal üçün channel_secrets sətri tapılmadı."
        )

    return channel, secrets


def upload_video(
    refresh_token: str,
    scopes: list[str],
    video_path: Path,
) -> str:
    credentials = Credentials(
        token=None,
        refresh_token=refresh_token,
        token_uri="https://oauth2.googleapis.com/token",
        client_id=GOOGLE_CLIENT_ID,
        client_secret=GOOGLE_CLIENT_SECRET,
        scopes=scopes,
    )

    youtube = build(
        "youtube",
        "v3",
        credentials=credentials,
        cache_discovery=False,
    )

    body = {
        "snippet": {
            "title": "AutoTube Studio – Private Upload Test",
            "description": (
                "Private technical upload test generated by "
                "AutoTube Studio. This video can be deleted."
            ),
            "tags": [
                "AutoTube Studio",
                "upload test",
            ],
            "categoryId": "22",
        },
        "status": {
            "privacyStatus": "private",
            "selfDeclaredMadeForKids": False,
        },
    }

    request = youtube.videos().insert(
        part="snippet,status",
        body=body,
        media_body=MediaFileUpload(
            str(video_path),
            mimetype="video/mp4",
            resumable=True,
        ),
    )

    response = None

    while response is None:
        status, response = request.next_chunk()

        if status:
            print(
                f"Upload: {round(status.progress() * 100)}%",
                flush=True,
            )

    return response["id"]


def main() -> None:
    work_dir = Path("worker-test-output")
    work_dir.mkdir(exist_ok=True)

    video_path = work_dir / "autotube-upload-test.mp4"

    print("Supabase bağlantısı qurulur...")
    supabase = create_client(
        SUPABASE_URL,
        SUPABASE_KEY,
    )

    channel, channel_secret = get_connected_channel(supabase)

    print(
        "Test kanalı:",
        channel["name"],
        channel["youtube_handle"],
    )

    refresh_token = decrypt_refresh_token(
        channel_secret["refresh_token_cipher"]
    )

    scopes = channel_secret.get("scopes") or [
        "https://www.googleapis.com/auth/youtube.upload",
        "https://www.googleapis.com/auth/youtube.readonly",
    ]

    print("6 saniyəlik test videosu hazırlanır...")
    create_test_video(video_path)

    print("Video Private olaraq YouTube-a yüklənir...")
    youtube_video_id = upload_video(
        refresh_token,
        scopes,
        video_path,
    )

    youtube_url = f"https://youtu.be/{youtube_video_id}"

    print("Upload uğurludur.")
    print("YouTube video ID:", youtube_video_id)
    print("YouTube URL:", youtube_url)

    supabase.table("events").insert(
        {
            "owner_id": (
                supabase.table("channels")
                .select("owner_id")
                .eq("id", channel["id"])
                .single()
                .execute()
                .data["owner_id"]
            ),
            "channel_id": channel["id"],
            "level": "info",
            "type": "youtube_upload_test",
            "message": "Private YouTube upload testi uğurla tamamlandı.",
            "payload": {
                "youtube_video_id": youtube_video_id,
                "youtube_url": youtube_url,
            },
        }
    ).execute()


if __name__ == "__main__":
    try:
        main()
    except Exception as error:
        print(
            f"TEST FAILED: {error}",
            file=sys.stderr,
        )
        raise
